### ISSUE TITLE
Support deterministic signing (RFC6979)

### ISSUE THREAD

**Issue by justusranvier** [btcsuite/btcwallet#146]
Deterministic ECDSA signatures protect against leaking private keys in the event of vulnerabilities in the system random number generator.

http://tools.ietf.org/html/rfc6979

**Comment by oleganza** [comment]
RFC6979 is implemented in this pull request in btcd/btcec repository: https://github.com/btcsuite/btcd/pull/360

**Comment by davecgh** [comment]
This has been implemented via btcsuite/btcd#360.  All signatures created by btcwallet as of this commit will be deterministic according to RFC6979.
