### ISSUE TITLE
waddrmgr: Optimize by using for each style functions for data lists

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcwallet#215]
The `Manager` provided by the waddrmgr package currently has various functions which return a slice of all associated data.  In particular, `ActiveAccountAddresses`, `AllAccountAddresses`, `AllAccounts`, and `AllActiveAddresses`.

While it is certainly convenient this way, these should be switched over to iterator style functions to enable better scalability.  As it stands, imagine if you have millions of active addresses.  Creating a slice of all of these takes a huge amount of memory and a non-trivial amount of time to generate.  In many cases, the caller might be skipping several of them anyways.  Accepting an iterator-style callback function to call with each entry, on the other hand, would allow iterating them one at a time therefore eliminate the need for huge memory allocations.

As an example, consider `AllActiveAddresses`.  The current signature is: `func (m *Manager) AllActiveAddresses() ([]btcutil.Address, error)`.  This should be changed to `func (m *Manager) ForEachActiveAddress(fn func(btcutil.Address) error) error`  This will allow the caller to in turn do:

```Go
err := m.ForEachActiveAddress(func(addr btcutil.Address) error {
	// Do something with each addr, possibly returning an error to stop
	// iteration and return the error from AllActiveAddresses.
	return nil
})
if err != nil {
	// Handle it.
}
```

In regards to implementation, to provide better efficiency for these, I would suggest the database should maintain appropriate indices for each of these in separate buckets.  Then, it is a simple matter of doing a `bucket.ForEach` on the appropriate bucket, creating the necessary type from the underlying raw data, and invoking the caller-provided function with the type instance.

**Comment by jrick** [comment]
Fixed by fbf744bc5e0cde6a0febf8772b32af320f6454a1.
