### ISSUE TITLE
Adding "Batch" to namespace

### ISSUE THREAD

**Issue by josephyzhou** [btcsuite/btcwallet#218]
Can we have batch similar to boltdb?

**Comment by davecgh** [comment]
That was a fairly recent addition to bolt.  I'm not against the idea, but I personally won't be able to get to implementing it any time soon.

If anyone wants to tackle a PR, that would be appreciated.

Alternatively, if you need something more quickly, perhaps something similar to https://github.com/boltdb/coalescer would be a relatively quick solution.

**Comment by jrick** [comment]
It's more work for other drivers to implement (think an in-memory backend, for example, which might make sense for some simnet situations) but I don't see this being done anytime soon in the future.

Why do you want this feature?

**Comment by jrick** [comment]
Closing this.  BoltDB Batch is useful for batching concurrent transactions together, but this is not our current bottleneck.  Instead, wtxmgr should perform more updates as part of the same transaction, ideally adding all transactions and marking all credits from a single block on a single DB transaction.  If concurrent transaction batching is needed after this, it can be added then.
