### ISSUE TITLE
walletpassphrase panic

### ISSUE THREAD

**Issue by tuxcanfly** [btcsuite/btcwallet#243]
I had this happen to me a few times when calling walletpassphrase, timeout 10:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x1 pc=0x82cd540]

    goroutine 68 [running]:
    runtime.panic(0x8567720, 0x8a04193)
            /usr/local/go/src/pkg/runtime/panic.c:279 +0xe9
    github.com/btcsuite/btcutil/hdkeychain.(*ExtendedKey).Child(0x0, 0x0, 0x71d6f501, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcutil/hdkeychain/extendedkey.go:202 +0x60
    github.com/btcsuite/btcwallet/waddrmgr.(*Manager).deriveKey(0x18c3e280, 0x349c1f80, 0x0, 0x0, 0x1, 0x20, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/waddrmgr/manager.go:418 +0x69
    github.com/btcsuite/btcwallet/waddrmgr.(*Manager).deriveKeyFromPath(0x18c3e280, 0x0, 0x0, 0x0, 0x18c22201, 0x20, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/waddrmgr/manager.go:553 +0x9c
    github.com/btcsuite/btcwallet/waddrmgr.(*Manager).Unlock(0x18c3e280, 0x3531d808, 0x4, 0x8, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/waddrmgr/manager.go:1328 +0xf34
    github.com/btcsuite/btcwallet/wallet.(*Wallet).walletLocker(0x18f7a280)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/wallet/wallet.go:554 +0x11c
    created by github.com/btcsuite/btcwallet/wallet.(*Wallet).Start
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/wallet/wallet.go:333 +0x17e

**Comment by davecgh** [comment]
These line number don't match up to master as of commit 948609f.  Can you either get a trace against master or post which commit on master it's against.

**Comment by tuxcanfly** [comment]
OK, will try to repro on master and update with the trace.

**Comment by davecgh** [comment]
Thanks.  I'm not 100% sure since the numbers don't line up, but I'm going to guess based on what's close.  The current code in deriveKey has a precondition that acctInfo.acctKeyPub will never be nil.  Given the error, there is a good bet some of the recently added code has broken this precondition.

**Comment by tuxcanfly** [comment]
Yeah, this happened when testing the current address changes so it might be related to that.

**Comment by tuxcanfly** [comment]
Sorry, this was most probably due to removing entries from `m.acctInfo` in `loadAccountInfo`
