### ISSUE TITLE
Enable mainnet by default

### ISSUE THREAD

**Issue by hjfreyer** [btcsuite/btcwallet#244]
Firstly, as a gopher and bitcoin enthusiast, I love what you're doing. The parts of the code I've read are lovely. Satoshi may have been prodigious at design but the code is... iffy. 

This is more a question than a request: at what point will btcwallet be ready for general availability? I'd love to switch over to the two-server architecture, but until there's a wallet app, there's no real reason for a consumer to use btcd.

**Comment by dajohi** [comment]
You can currently use btcwallet with mainnet by using the --mainnet argument or adding mainnet=1 to btcwallet.conf.   There are a few more changes we'd like to get in before making mainnet the default.  We also are improving the test coverage. 

On a side note, I currently use btcwallet on mainnet without problems.

**Comment by jrick** [comment]
We were thinking of switching to mainnet by default once all of the "big ticket" items are completed and we switch from alpha to beta.  That means for sure no more big db changes, and possibly SPV support and a cleaner client API to deprecate the bitcoind-compatible one.  But those last two items aren't show stoppers if you're happy with the existing API and plan on using btcd over RPC for chain services.

**Comment by hjfreyer** [comment]
I assume these "big DB changes" won't actually effect the wallet per se,
right? Is the way the master secret(s) is stored likely to change, or are
you just talking about other, recoverable metadata like transactions?

**Comment by jrick** [comment]
Transactions mostly (recovering via rescan, especially on mainnet, is tedious and we'd like to avoid that after beta), but there are some changes we need to make to the address manager as well (but I think all of those can be done via an upgrade step at startup)

**Comment by jrick** [comment]
Closing for now.  Mainnet is still easily enabled but we don't want to make it default yet until the previously mentioned features are in.
