### ISSUE TITLE
`listsinceblock` seems to miss unconfirmed transactions

### ISSUE THREAD

**Issue by arnuschky** [btcsuite/btcwallet#263]
It appears that btcwallet's `listsinceblock` call doesn't contain unconfirmed transactions known to btcd and btcwallet (checked via `gettransaction`).

**Comment by arnuschky** [comment]
Confirmed. Even worse, btcwallet lists confirmed transactions since given block twice.

**Comment by jrick** [comment]
Thanks, I'll get the unconfirmed txs fixed.  Core's help is misleading here (it says it includes txs *from blocks* since the specified block, but then continues to include all unmined transactions as well).

Also, I would highly recommend not using this RPC as it uses the listtransactions result format, which is next to worthless when it comes to programmable access to the wallet, and is highly misleading about many things when used by a command line client to interface with wallet.  That being said, there is no good alternative yet.

**Comment by arnuschky** [comment]
Replicated the double-inclusion of confirmed transactions. Strangely, not all of them.

**Comment by jrick** [comment]
We're missing the vout field currently (I'll update btcjson to fix that) but you're probably seeing the same objects twice because the results are duplicated for each wallet output.

**Comment by arnuschky** [comment]
I doubt that, as there was only one transaction listed by bitcoin core with each hash.

**Comment by jrick** [comment]
Can you update to latest wallet and then show an example of this?

**Comment by jrick** [comment]
After taking another look at Core's implementation of listunspent, I feel like their implementation isn't doing what is expected.  The help text claims the following:

`
            "2. target-confirmations:    (numeric, optional) The confirmations required, must be 1 or more\n"
`

The second parameter is then given a default of 1 and the handler errors if the user provided a number less than 1.  It would make sense to include mempool transactions as well when the target number of confirmations is 0, but that's now allowed.

Next, it creates the listtransactions result array.  Here, it only includes the transaction that the height is -1 (mempool height) or the transaction is mined in a block after the hash in the first parameter.  Including mempool transactions in this step seems like an oversight, or target-confirmations is a very poorly named parameter with an even more ambiguous help description.

Finally, it returns the block hash for the next listsinceblock call.  Here is the only place where it uses the target confirms parameter, by returning the hash of the block with the target number of confirmations.

I can modify wallet to match this behavior, but to me it seems like there was not a whole lot of thoughtfulness put into this API.

**Comment by arnuschky** [comment]
Yes, it's about the most confusing and worst call of that API. But it's crucial, as there's no other way to get unconfirmed transactions. From the wiki:

> listsinceblock	[blockhash] [target-confirmations]	Get all transactions in blocks since block [blockhash], or all transactions if omitted. [target-confirmations] intentionally does not affect the list of returned transactions, but only affects the returned "lastblock" value.

See https://github.com/bitcoin/bitcoin/pull/199#issuecomment-1514952 for the reasoning behind this.

**Comment by jrick** [comment]
If you still see the duplicate entries in listsinceblock or any other rpc with the listtransactions result format, you can open another issue.

**Comment by arnuschky** [comment]
Ok, will do. I'll test this now.

**Comment by arnuschky** [comment]
Unconfirmed tx are now included alright. Thanks for the fix.
