### ISSUE TITLE
Seeing Error "WLLT: Could not lock wallet: address manager is locked"

### ISSUE THREAD

**Issue by arnuschky** [btcsuite/btcwallet#270]
Log shows `[ERR] WLLT: Could not lock wallet: address manager is locked` from time to time.

No obvious log entries around occurrence; log lists `WLLT: Marked address ...` before and after but with several seconds to minutes distance. Running with loglevel debug.

**Comment by jrick** [comment]
I believe I found the fix.  Just to confirm, were you explicitly locking the wallet, and the error was printed when the unlock timer expired?

**Comment by arnuschky** [comment]
Possible. The software I use for testing is actively locking the wallet, and on long operations it might happen that the unlock timer expired before that.

I increased that timer considerably now to check whether this was the cause.

**Comment by arnuschky** [comment]
I can confirm this, warnings went away after I disabled explicitly locking the wallet.

**Comment by jrick** [comment]
Ok thanks, pr'ing the fix in a bit.

**Comment by arnuschky** [comment]
Tested it, patch works, thanks.
