### ISSUE TITLE
`listsinceblock` transaction format differences to bitcoin core

### ISSUE THREAD

**Issue by arnuschky** [btcsuite/btcwallet#272]
Back to the worst call of a crappy API. :( Sorry for this...

1) btcwallet does not list `blockindex` for transactions in `listsinceblock`.

2) btcwallet lists a positive fee for transactions of category `send` while bitcoin core lists a negative fee.

**Comment by jrick** [comment]
blockindex is no longer tracked.  It was dropped from wtxmgr in preparation for SPV support later.  We can't report it.

The negative fee is inane but I can switch it.

**Comment by arnuschky** [comment]
Ok, great, thanks. Agree wrt to negative fee.
