### ISSUE TITLE
'Connection to Bitcoin RPC chain server unsuccessful'

### ISSUE THREAD

**Issue by haarts** [btcsuite/btcwallet#297]
I'm running the latest btcd and btcwallet. I have successfully created a wallet with the `--create` flag. But now when I run `$ btcwallet` I get:

```
03:37:53 2015-06-30 [INF] WLLT: Opened wallet
03:37:53 2015-06-30 [INF] BTCW: RPCS: RPC server listening on 127.0.0.1:18332
03:39:08 2015-06-30 [WRN] BTCW: Connection to Bitcoin RPC chain server unsuccessful -- available RPC methods will be limited
```

Is that something I should worry about? And what is a `chain server` anyway?

**Comment by jrick** [comment]
Chain server refers to btcd in this case; it's the server that provides chain services.

Check that you are running btcd with the rpcuser/rpcpass options (or it won't run the RPC server), with --testnet (btcwallet defaults to testnet for now), and if you're not connecting to a localhost btcd, be sure to copy the autogenerated ~/.btcd/rpc.cert to your local machine and point to it with the cafile option.

**Comment by haarts** [comment]
Aha! That was it. My `btcd` ran mainnet and the client `testnet` (as evident from the `~/.btcwallet/testnet` directory). Creating a wallet on mainnet and starting btcwallet with the `--mainnet` flag resolved the issue. 
Thanks a lot.
