### ISSUE TITLE
Simultaneous btcd and btcwallet startup is flaky

### ISSUE THREAD

**Issue by hjfreyer** [btcsuite/btcwallet#318]
I'm running btcd and btcwallet in Kubernetes, and sometimes btcwallet will give up on connecting to btcd by the time btcd is ready for requests.

There are many crappy-to-decent solutions to this. I think a reasonable one would be a --require_server flag in btcwallet, which will cause btcwallet to crash if it can't connect to btcd in some amount of time. Assuming a reasonable job control mechanism, after a couple crashes at most it should be able to connect to btcd, and if it can't, a crashloop is more obvious than silently limited behavior.

**Comment by jrick** [comment]
Another option would be a numeric value for the number of seconds or minutes that it should continue reattempting the connection.  If the value is positive, it will continue waiting for that long but no longer (giving up but not crashing or exiting).  Otherwise, if the value is zero, it will never give up on the connection.

**Comment by toddfries** [comment]
My own opinion on the matter is that btcwallet should persist in attempting to connect to the server for the first time.   If you once connect to btcd, and stop btcd, a year later btcwallet will still be trying...

**Comment by jrick** [comment]
@toddfries that's what the 0 value in my proposed option would do.  We could even make that the default, but I would have to shuffle some code around and make sure the wallet is still usable for tasks that don't require btcd when it's disconnected (like dumping private keys).

Note that this only applies to transient errors.  Permanent errors (e.g. bad cert) would still log an error and then no longer attempt the connection.

**Comment by jrick** [comment]
Closing this one since wallet never stops trying the btcd connection anymore, either on initial startup or after it notices a disconnect.
