### ISSUE TITLE
signmessage fails for eligius ??

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcwallet#323]
<a href="https://github.com/toddfries"><img src="https://avatars1.githubusercontent.com/u/1231619?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [toddfries](https://github.com/toddfries)**
_Friday Oct 16, 2015 at 15:04 GMT_
_Originally opened as https://github.com/btcsuite/btcd/issues/513_

----

It is easy enough to verify.   Find an address in your wallet, you don't even have to send coins to eligius to do this, just put the address in at:

 http://eligius.st/~wizkid057/newstats/mystats.php

and then go to 'Configuration Options' and then make any change, note the message to sign below, unlock your wallet, do:

   btcctl signmessage "&lt;address&gt;" "&lt;message&gt;"

and note eligius claims this fails.  If you can succeed where I have failed, I'll be glad to have done something wrong....

**Comment by toddfries** [comment]
thanks for moving this to the proper location, i'll try to pay attention to where i'm filin bugs next time *grin*

**Comment by davecgh** [comment]
This was confirmed as an issue and fixed by #324.  See the commit message for details.
