### ISSUE TITLE
Default to mainnet

### ISSUE THREAD

**Issue by jrick** [btcsuite/btcwallet#383]
After several years of development I think it's time to change this.  The software has been used in production on mainnet for quite some time on various projects, and we have no reason to deter other users from using the software on mainnet either.

**Comment by jrick** [comment]
I'll make this change after a mutex has been added to walletdb to prevent closing the db while bolt transactions are still active.

Other database fixes (such combining keys, accounts, and transaction handling into a single location) will be fixed after, and will need to have a DB upgrade anyways.

**Comment by davecgh** [comment]
Agreed
