### ISSUE TITLE
legacyrpc RPC handler functions should be unexported

### ISSUE THREAD

**Issue by jrick** [btcsuite/btcwallet#435]
These have no business being called by other packages (their implementations are internal to the RPC server implementation) and their signatures are free to change at any time (as has happened before).

Unexporting these would also help consistency with the gRPC server stub implementations, which are also unexported (actually, they are exported methods on an unexported type in order to implement the stub interface, but similar idea).

**Comment by davecgh** [comment]
I completely agree.  This is something that has bothered me for quite some time now - basically since I first dug into wallet.
