### ISSUE TITLE
btcctl tries to make btcd.conf when using wallet

### ISSUE THREAD

**Issue by carryforward** [btcsuite/btcwallet#460]
when I use btcctl to access a wallet, it tries to make a btcd.conf in the .btcd directory.  I do not have btcd on the same computer as the wallet, and automatically making a config file is silly when I am not even trying to access the program that uses it.

```
btcctl --wallet --testnet -u username -P password listaccounts
Error creating a default config file: open /home/factom/.btcd/btcd.conf: no such file or directory
```

perhaps if I were trying to control btcd, this would make sense, but not with the wallet.

**Comment by jrick** [comment]
btcctl is part of the btcd repo.  can you open the issue there?

**Comment by carryforward** [comment]
moved to https://github.com/btcsuite/btcd/issues/875
