### ISSUE TITLE
Update the grpc client for go with grpc version4 

### ISSUE THREAD

**Issue by macnibblet** [btcsuite/btcwallet#465]

**Comment by jrick** [comment]
It's out of date, but that's why we use glide (so that we can reliably build without dependencies changing underneath us causing breakage).  If you are building with `go get`, see the README for the new build instructions.

That said i'll look into updating dependencies since the are quite a bit behind.

**Comment by macnibblet** [comment]
I'm not sure I follow you, I have installed the latest version and run the `glide install` command. But I don't see how that will rebuild the client ?

**Comment by jrick** [comment]
Oh! I missed the word client from your issue.  Which code are you talking about exactly?  The example clients in the documentation, or something else?

**Comment by macnibblet** [comment]
@jrick Soo after six months I'm working on this project again. The problem I have is that our entire system relies on grpc v4 and the walletrpc code uses grpc v2.

This line will cause our application to fail at compile time due to the v2 check. 
https://github.com/btcsuite/btcwallet/blob/master/rpc/walletrpc/api.pb.go#L82

**Comment by macnibblet** [comment]
Just noticed it's proto v2 and grpc v3 and that i refererenced the wrong line.

Is the line Is causing compiler errors for me
https://github.com/btcsuite/btcwallet/blob/master/rpc/walletrpc/api.pb.go#L848

It might just be a question of forking the project, updating the generated code and running again ?

**Comment by jrick** [comment]
I'll update it to the latest grpc release.
