### ISSUE TITLE
Grpc LoaderService.OpenWallet will not re-open the database

### ISSUE THREAD

**Issue by macnibblet** [btcsuite/btcwallet#466]
Heya,

I'm pretty much a rookie to both golang and bitcoin is general so I'm sorry if this is a stupid question. But I'm assuming it's good practice to close the wallet after using it? And doing so it will close the database connection. But on the next run of my application, it calls the `OpenWallet` method, which works but OpenWallet never re-opens the database connection making any subsequent calls after that always fail. 

I'm not sure if this a major concern or if I should just ignore the OpenWallet error if I start my application and it's already open. But I'm not sure how to access the error code from the error returned ?

**Comment by jrick** [comment]
That RPC was added as a way to do "clean" shutdown of a child btcwallet process by closing everything important and then just killing the process, so there's no way to open, close, and reopen the wallet all in the same application lifetime.  There's no need to close the wallet when you aren't using it while keeping the process running.
