### ISSUE TITLE
QUESTION: Is a fully fledged btcd node required?

### ISSUE THREAD

**Issue by cumaa** [btcsuite/btcwallet#477]
Hi

quick question, is it necessary to run a fully fledged btcd node in order to be able to use the wallet? 
If yes, are there public btcd nodes? If yes, does a btcd node need to download the whole blockchain?

Best

**Comment by jrick** [comment]
Yes, a full node is required.

To my knowledge there are no public nodes with the RPC server freely accessible, which is required to use the wallet.
