### ISSUE TITLE
Fatal error when trying to launch

### ISSUE THREAD

**Issue by MJeorrett** [btcsuite/btcwallet#480]
I have just downloaded source and built it.  Tried to launch with --create flag but get the following error:
```bash
$ ./btcwallet.exe --simnet --create
Enter the private passphrase for your new wallet: Unable to create wallet: The handle is invalid.
```

Same happens when installed with msi.

I tried debugging and error is returned from syscall made in second line of ReadPassword function in util_windows.go

**Comment by jrick** [comment]
Can you try it in cmd or powershell?

**Comment by MJeorrett** [comment]
Hi thanks, cmd works.  Must be something to do with using gitbash on windows.
