### ISSUE TITLE
strange code style, defer unlock before lock

### ISSUE THREAD

**Issue by qshuai** [btcsuite/btcwallet#531]
```
// CreateNewWallet creates a new wallet using the provided public and private
// passphrases.  The seed is optional.  If non-nil, addresses are derived from
// this seed.  If nil, a secure random seed is generated.
func (l *Loader) CreateNewWallet(pubPassphrase, privPassphrase, seed []byte,
	bday time.Time) (*Wallet, error) {

	defer l.mu.Unlock()
	l.mu.Lock()

	if l.wallet != nil {
		return nil, ErrLoaded
	}
```

**Comment by qshuai** [comment]
@Roasbeef PTAL

**Comment by jrick** [comment]
This was my code.  I don't work on this project anymore, so I don't care if it's changed, but there was a reason for this.  Deferring a function call has a (small) runtime cost, and doing so inside the critical section can increase lock contention.

**Comment by qshuai** [comment]
> This was my code. I don't work on this project anymore, so I don't care if it's changed, but there was a reason for this. Deferring a function call has a (small) runtime cost, and doing so inside the critical section can increase lock contention.

Seem reasonable!
