### ISSUE TITLE
unable to use "SendFrom" 

### ISSUE THREAD

**Issue by johnsneakers** [btcsuite/btcwallet#539]
it return err =>  {"result":null,"error":{"code":-32603,"message":"account  1 not found"},"id":9}

I checked the source code and found that the account is not in the cache：
![image](https://user-images.githubusercontent.com/3086958/44959529-816db680-af22-11e8-86ce-b5806e086f84.png)

emm..  go to step 2.. looks like no data found in database,  so  where is account storage?
Is it something I forget when I created my account?
(i create account by call CreateNewAccount("pwd") function)

**Comment by mohanson** [comment]
So do I. Recurring step in btcctl:

```
$ btcctl --wallet listaccounts
{
  "default": 0,
  "imported": 0,
  "user1": 20,
  "user2": 0.5
}

$ btcctl --wallet sendfrom user1 STzjrY1Y3PGMPREFUuxGwHrG6q2n7sR4qP 0.1
-32603: account 1 not found
```

**Comment by johnsneakers** [comment]
nobody here ..

**Comment by johnsneakers** [comment]
> it return err => {"result":null,"error":{"code":-32603,"message":"account 1 not found"},"id":9}
> 
> I checked the source code and found that the account is not in the cache：
> ![image](https://user-images.githubusercontent.com/3086958/44959529-816db680-af22-11e8-86ce-b5806e086f84.png)
> 
> emm.. go to step 2.. looks like no data found in database, so where is account storage?
> Is it something I forget when I created my account?
> (i create account by call CreateNewAccount("pwd") function)
