### ISSUE TITLE
Wallet doesn't sync if initial rescan starts one block behind chain backend.

### ISSUE THREAD

**Issue by roeierez** [btcsuite/btcwallet#585]
In the cases where the wallet starts and its initial rescan only need to catch up one block, RescanFinished notification is not triggered causing it not to switch into "synced" state.
Only restart or another mined block fixes this.

I bumped into this bug using LND and here is my investigation:

The syncToChain flag in LND will only be evaluated to true if the wallet “ChainSynced” function returns true (https://github.com/btcsuite/btcwallet/blob/master/wallet/wallet.go#L281)
This flag is set after first rescan has finished here: https://github.com/btcsuite/btcwallet/blob/master/wallet/chainntfns.go#L176
The problem I see is that sometimes the first rescan just doesn’t end and only when another block is mined it triggers the “RescanFinished” notification, causes the wallet to be marked as “synced”.
The racy condition is when the chain backend (I am using neutrino) is exactly one block ahead of the wallet “SyncedTo” value. In that case the wallet starts a rescan, the rescan notifies of the next block and filteredBlock here: https://github.com/lightninglabs/neutrino/blob/master/rescan.go#L722
The RescanFinished notification is triggered inside the “onFilteredBlockConnected” callback here: https://github.com/btcsuite/btcwallet/blob/master/chain/neutrino.go#L523 but only if the “s.lastProgressSent=true”. This flag is set on the onBlockConnected callback (https://github.com/btcsuite/btcwallet/blob/master/chain/neutrino.go#L593) which happens to be called AFTER the “onFilteredBlockConnected” callback, causing it not to trigger the RescanFinished notification until after the next block arrives.

**Comment by Roasbeef** [comment]
We've decided to fix this issue in neutrino itself by swapping the order of the `onBlockConnected` and `onFilteredBlockConnected` calls.
