### ISSUE TITLE
[Illumos] Build Failure - Outdated golangcrypto ssh/terminal prevents successful compilation on Solaris systems

### ISSUE THREAD

**Issue by kayront** [btcsuite/btcwallet#638]
See: https://github.com/lightningnetwork/lnd/issues/3431

I was able to get lnd compiled (it was failing at btcsuite) by copying the newer golandcrypto ssh/terminal files over.

I am in the process of creating instructions and making it easier for folks using Illumos (or Solaris) systems to get going with this, but with the manual shuffling of files around it's a nightmare.

Any chance you could incorporate the newer changes in golangcrypto ssh/terminal (util_solaris.go is missing in your fork) ?

**Comment by kayront** [comment]
Alright. What is needed to make the change?

I would like to create a package for lnd soon(TM) and this little problem could get ugly to fix - meanwhile it seems to be a very simple fix in btcsuite.

I'm in no hurry to create the package at the moment, still working on a few other things. Will you guys take care of it fixing the `golangcrypto` stuff in the mean time?

**Comment by wpaulino** [comment]
@kayront see #639 for the fix.
