### ISSUE TITLE
Multi Wallet support

### ISSUE THREAD

**Issue by iangregsondev** [btcsuite/btcwallet#680]
Hi,

I wonder if somebody can confirm a few things. I was hoping to add wallet functionality to btcd and found this project.

I was wondering at what stage this is at? 

I also noticed it stated it was a single user wallet instance, does this mean that its not possible to create multiple wallets? This is what is displayed on the github

```
btcwallet is a daemon handling bitcoin wallet functionality for a single user. 
```

I was hoping to be able to create multiple wallets that can be assigned to a user or different users. Is this possible or is it on the horizon?

As far as the system is concerned, I suppose it wouldn't matter to able to create for different users - this really isn't needed, just the possibility to create different wallets that supports their own different addresses.

I did see the following grpc create wallet https://github.com/btcsuite/btcwallet/blob/master/rpc/documentation/api.md#createwallet

So I am a little confused on whether it supports only a single wallet or multiple wallets ?

For example, if it supports creating multiple wallets then how to create an address on a "specific" wallet ?

Or for example, how to execute this on a specific wallet ? https://github.com/btcsuite/btcwallet/blob/master/rpc/documentation/api.md#gettransactions

I was using bitcoire core wallets in the past but when a new wallet is created you had to add this into the conf file so that it is reloaded on next restart.

Can anyone offer any insight on the current state of the wallet and if it supports the above ?

I was also wondering if bip39 is supported or on the horizon to be supported ?

Thanks in advance

Ian

**Comment by jcvernaleo** [comment]
I'm not 100% sure I follow what you mean by multiple wallets.  A single running btcwallet instance will have a single `wallet.dat` file with multiple addresses in it.

If you want to support multiple users your best bet would probably to run multiple instances of btcwallet, each with their own data directory and credentials (and therefore their own `wallet.dat` file).  These can all talk to a single btcd instance so no need for multiple copies of the blockchain.

**Comment by iangregsondev** [comment]
HI @jcvernaleo , yes exactly multiple wallets - for example - en bitcoin core and bcoin. You have one instance but it serves multiple wallets.

It's not required to run another instance of the wallet server software. I am trying to integrate some enterprise software - which potentially there could be more than 20 users and I don't want to run 20 instances..

Currently, our setup is

Bitcoin Core (1 full node) and BCOIN running in SPV mode talking to bitcoin core (only trusted full node) BCOIN provides multiple wallets.

I was hoping to move over to btcd and I thought it would be ideal to use btcd with btcd wallet - but this sounds like it woudn't work.

Although moving over to btcd is still do-able.

Would be 

BTCD (1 full node) and BCOIN running in SPV mode talking to bitcoin core (only trusted full node) BCOIN provides multiple wallets.
