### ISSUE TITLE
Add User Specified Labels to Published Transactions

### ISSUE THREAD

**Issue by carlaKC** [btcsuite/btcwallet#693]
#### Feature Request
The ability to add a user-specified label to the transactions that btcwallet publishes is a useful feature for users with the requirement to audit/ reconcile their on-chain activity. This feature request arises from the need to store labels for on chain transactions to allow users to more easily audit their nodes in [lnd](https://github.com/lightningnetwork/lnd/issues/2597).

I would like to work on this myself, but this change would require a database migration, so I’d like to open up discussion before submitting a PR. Specifically whether this is a change that would be welcome in btcwallet, and whether the approach outlined below is suitable. 

#### Proposed Approach
The current schema for writing transactions to disk (copied from wtxmgr/db.go) ends with a variable length field, which means a new field cannot simply be added. 
```
Key:
  [0:32]  Transaction hash (32 bytes)
  [32:36] Block height (4 bytes)
  [36:68] Block hash (32 bytes)
Value:
  [0:8]   Received time (8 bytes)
  [8:]    Serialized transaction (varies)
```

Migration:
* Iterate through each txRecord, reading from disk
* Get length of serialized transaction, and write to disk in LV format:
  ```
  [0:8]           Received time (8 bytes)
  [8:16]          Len(Serialized transaction)
  [16: len(tx)]  Serialized transaction
  ```

This migration will allow for the addition of new fields. In the case of a user provided label, which is optional, a similar LV format would be used:
```
[0:8]           Received time (8 bytes)
[8:16]         Len(Serialized transaction)
[+len(tx)]    Serialized transaction
[+8]:          Len(user label)
[+len(label)]   User Label
```

**Comment by Roasbeef** [comment]
cc @wpaulino

**Comment by wpaulino** [comment]
We could also avoid the migration by storing the labels under a distinct bucket mapping `tx_hash` -> `label`. I have a slight preference towards this approach just to avoid the migration, but either sounds good to me.
