### ISSUE TITLE
Hot wallet

### ISSUE THREAD

**Issue by aminNazarii** [btcsuite/btcwallet#694]
how can i make a main wallet and multi address for main wallet?
i want to have a main wallet with many address when deposit to one of these address fund to main wallet

**Comment by Aimeelu668** [comment]
不过自己开发的钱包都是热钱包机制，节点同步慢，归集非常麻烦，最重要的是这些私钥存在服务器上很危险，天天被黑客盯着。当时我们平台有50多万会员，为了解决钱包问题折腾了一年，最终放弃了，选择了优盾钱包 https://www.uduncloud.com 。通过API直接接入就行，有独立客户端操作审核、归集等，私钥也是自己在客户端上管理，服务器上不存。用了快一年，没有出现安全问题，财务都反馈说体验很好。我们也终于可以专注于业务开发了。推荐试试

**Comment by Aimeelu668** [comment]
楼主大大总结的很到位！不过自己开发的钱包都是热钱包机制，节点同步慢，归集非常麻烦，最重要的是这些私钥存在服务器上很危险，天天被黑客盯着。当时我们平台有50多万会员，为了解决钱包问题折腾了一年，最终放弃了，选择了优盾钱包 https://www.uduncloud.com  。通过API直接接入就行，有独立客户端操作审核、归集等，私钥也是自己在客户端上管理，服务器上不存。用了快一年，没有出现安全问题，财务都反馈说体验很好。我们也终于可以专注于业务开发了。推荐试试

**Comment by Roasbeef** [comment]
WE now support pubkey import, so various forms of watch-only wallets are possible.

**Comment by msafi** [comment]
@Roasbeef is this feature documented somewhere? Is it possible to import an extended pubkey and generate a watch-only **HD** wallet?

**Comment by guggero** [comment]
See https://github.com/btcsuite/btcwallet/pull/676.

You can import each account one by one. But you cannot build a full HD wallet from an xpub because hardened keys (with the apostrophe in the derivation path) cannot be derived from an xpub.

**Comment by msafi** [comment]
@guggero okay, can a feature be implemented where the user is asked for both the xprv and xpub which are used to build the watch-only HD wallet before the keys are removed from memory (assuming the user is responsible for maintaining the keys)? If possible, then can it also be achieved with hardware wallets which don't share the keys?

(I'm starting to think this is a major drawback of hardened derivation paths. Given these trade-offs I'd prefer regular derivations paths and the ability to conveniently create watch-only wallets.)
