### ISSUE TITLE
Error on install - txauthor/go.mod: no such file or directory

### ISSUE THREAD

**Issue by bensig** [btcsuite/btcwallet#756]
Running `GO111MODULE=on go install -v . ./cmd/...` results in this error

go: github.com/btcsuite/btcwallet/wallet/txauthor@v1.0.0 (replaced by ./wallet/txauthor): reading wallet/txauthor/go.mod: open /home/username/go/pkg/mod/github.com/btcsuite/btcwallet@v0.12.1-0.20210519225359-6ab9b615576f/wallet/txauthor/go.mod: no such file or directory

**Comment by bensig** [comment]
Tried to download again using `go get github.com/btcsuite/btcwallet`

Got this output:

go: downloading github.com/btcsuite/btcwallet v0.12.0
go: downloading github.com/btcsuite/btcd v0.21.0-beta.0.20210426180113-7eba688b65e5
go: downloading google.golang.org/grpc v1.18.0
go: downloading github.com/btcsuite/btcutil/psbt v1.0.3-0.20201208143702-a53e38424cce
go: downloading github.com/golang/protobuf v1.4.2
go: downloading google.golang.org/genproto v0.0.0-20190201180003-4b09977fb922
go: downloading golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd
go: downloading golang.org/x/text v0.3.1-0.20180807135948-17ff2d5776d2
# github.com/btcsuite/btcwallet/wallet
go/pkg/mod/github.com/btcsuite/btcwallet@v0.12.0/wallet/createtx.go:148:43: cannot use changeSource (type *txauthor.ChangeSource) as type txauthor.ChangeSource in argument to txauthor.NewUnsignedTransaction
go/pkg/mod/github.com/btcsuite/btcwallet@v0.12.0/wallet/createtx.go:330:16: undefined: txsizes.NestedP2WPKHPkScriptSize
go/pkg/mod/github.com/btcsuite/btcwallet@v0.12.0/wallet/createtx.go:358:42: invalid composite literal type txauthor.ChangeSource
go/pkg/mod/github.com/btcsuite/btcwallet@v0.12.0/wallet/psbt.go:198:44: cannot use changeSource (type *txauthor.ChangeSource) as type txauthor.ChangeSource in argument to txauthor.NewUnsignedTransaction

Here is my go env:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/username/.cache/go-build"
GOENV="/home/username/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/username/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/username/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/7736"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/7736/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build411300299=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by bensig** [comment]
This works for installation until the go deps are figured out:

```
git clone https://github.com/btcsuite/btcwallet.git && cd btcwallet && make install
```

**Comment by Roasbeef** [comment]
This was fixed (main module was depending on an older version).
