### ISSUE TITLE
Add TxOut output scripts and values to ListLeasedOutputs

### ISSUE THREAD

**Issue by hitanshu-mehta** [btcsuite/btcwallet#793]
Currently, [ListLeasedOutputs](https://github.com/btcsuite/btcwallet/blob/50ea8d1125561279f9c9af1e46bea16ca414b4a5/wallet/wallet.go#L2714)  only return lock id, expiration, and outpoint of locked Txn output. 
A proposal is to add output scripts and values in the response. The use case for these data has been raised at [lnd](https://github.com/lightningnetwork/lnd/issues/5202). It will increase the visibility of locked funds and can be helpful with auditing.

**Comment by guggero** [comment]
Thanks for opening the issue. I agree that additional information of the UTXO would be great to have in the list of leased/locked outputs. IMO you can just start implementing and then create a PR. Ping me for a review.
There's quite some overlap of maintainers between `lnd` and `btcwallet` so I don't think you need to wait for "official approval" before starting the implementation if a feature is seen as useful in `lnd`.
