### ISSUE TITLE
Bitcoind client instead of Btcd for chain service?

### ISSUE THREAD

**Issue by 99Percent** [btcsuite/btcwallet#839]
Is it possible to use bitcoind as the chain backend for btcwallet?

I cannot find any specific instructions on how to configure this anywhere.

**Comment by Roasbeef** [comment]
Yes, `lnd` does this. It isn't exposed w/ the default `btcwallet` binary though. However you can instantitate all the relevant modules yourself to create a new btcwallet-only wrapper CLI/daemon.

**Comment by 99Percent** [comment]
I would need specific instructions on how to do this, or should I just use ```lnd``` as my wallet service instead of ```btcwallet```?

**Comment by Roasbeef** [comment]
Yeah if you want things to just work as is, I'd recommend lnd. Check out
the api docs: https://api.lightning.community/ and the `WalletKit` service.

**Comment by 99Percent** [comment]
Alternately, any instructions or pointers on how to use the bitcoind as the chain in btcwallet would be greatly appreciated.

**Comment by 99Percent** [comment]
Ok, I figured it out.

We use the GetTransactions in the Lightning grpc service. 
To get notified of new transactions, we can put a hook in the ChainNotifier RegisterBlockEpochNtfn.

I do think GetTransactions belongs more in the WalletKit service.
