### ISSUE TITLE
Send Raw Transaction Error

### ISSUE THREAD

**Issue by ChungKiet** [btcsuite/btcwallet#862]
Hi guys, I've used the function SendRawTransaction in btcwallet and catch this error:
 TX rejected: orphan transaction 52e27563ca5373f2d15c004a0a63825ea270c2cd721e6abc25b24d538691ef7b references outputs of unknown or fully-spent transaction  ....
Can you suggest me the solution for this problem?

Thanks

**Comment by guggero** [comment]
Some of the inputs you are referencing either are not known to the node you're sending the TX to (so not confirmed and not in the mempool) or are already spent. Without any more information about the TX that's all that can be said.

Closing as the TX is invalid as pointed out by the error message.
