### ISSUE TITLE
[golang] get an addresse's full tx history

### ISSUE THREAD

**Issue by r3nor** [btcsuite/btcwallet#938]
i am trying to use this as a golang module for an app, I am wondering how can I get the full tx history for an address without needing to go through all addresses of the wallet, just get that addresse's transactions

**Comment by r3nor** [comment]
i have tried using listbyaddress, but the function from the btcwallet client does not accept any parameter and it returns all the tx from all addressses

**Comment by Roasbeef** [comment]
You can use the address index in `btcd` for that: https://github.com/btcsuite/btcd/blob/master/sample-btcd.conf#L276-L278
